DROP DATABASE IF EXISTS THUNTDB;

CREATE DATABASE THUNTDB;

use THUNTDB;

CREATE TABLE USER (
    USER_ID int NOT NULL AUTO_INCREMENT,
    USER_EMAIL varchar(255) UNIQUE NOT NULL,
    USER_PASS varchar(60) NOT NULL,
    USER_LOW int NOT NULL,
    PRIMARY KEY (USER_ID)
);

